services:
  postgres:
    image: postgres:17.6
    restart: always
    container_name: n8n-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker_postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - n8n-net

  redis:
    image: redis:7-alpine
    restart: always
    container_name: n8n-redis
    ports:
      - "6379:6379"
    networks:
      - n8n-net

  n8n-cloud:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: n8n-cloud-custom:latest
    restart: always
    container_name: n8n-cloud
    environment:
      # ==== Code Node (JS): liberar built-ins e externos ====
      NODE_FUNCTION_ALLOW_BUILTIN: ${NODE_FUNCTION_ALLOW_BUILTIN}
      NODE_FUNCTION_ALLOW_EXTERNAL: ${NODE_FUNCTION_ALLOW_EXTERNAL}

      # ==== n8n ====
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: ${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      N8N_RUNNERS_ENABLED: ${N8N_RUNNERS_ENABLED}
      N8N_EXECUTIONS_PROCESS: ${N8N_EXECUTIONS_PROCESS}
      N8N_PUSH_BACKEND: ${N8N_PUSH_BACKEND}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_TEMPLATES_ENABLED: ${N8N_TEMPLATES_ENABLED}
      N8N_DIAGNOSTICS_ENABLED: ${N8N_DIAGNOSTICS_ENABLED}
      N8N_HIRING_BANNER_ENABLED: ${N8N_HIRING_BANNER_ENABLED}
      WEBHOOK_URL: ${WEBHOOK_URL}

      # ==== Banco do n8n (Postgres) ====
      DB_TYPE: ${DB_TYPE}
      DB_POSTGRESDB_DATABASE: ${DB_POSTGRESDB_DATABASE}
      DB_POSTGRESDB_HOST: ${DB_POSTGRESDB_HOST}
      DB_POSTGRESDB_PORT: ${DB_POSTGRESDB_PORT}
      DB_POSTGRESDB_USER: ${DB_POSTGRESDB_USER}
      DB_POSTGRESDB_SCHEMA: ${DB_POSTGRESDB_SCHEMA}
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}

      # ==== Fila (Redis) ====
      EXECUTIONS_MODE: ${EXECUTIONS_MODE}
      QUEUE_BULL_REDIS_HOST: ${QUEUE_BULL_REDIS_HOST}
      QUEUE_BULL_REDIS_PORT: ${QUEUE_BULL_REDIS_PORT}
      QUEUE_BULL_REDIS_DB: ${QUEUE_BULL_REDIS_DB}

      # ==== TZ ====
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${TZ}

    ports:
      - "5678:5678"
    volumes:
      - data:/home/node/.n8n
      - ./scripts/:/data/scripts/
      - ./credential/:/data/credential/
      - ./workflow/:/data/workflow/
    depends_on:
      - postgres
      - redis
    networks:
      - n8n-net

volumes:
  data:

networks:
  n8n-net:
    driver: bridge
